# Generated by Django 5.1.4 on 2025-01-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200, null=True)),
                ('book_type', models.CharField(choices=[('Paperback', 'Paperback'), ('Hardcover', 'Hardcover')], max_length=10, null=True)),
                ('price', models.FloatField(null=True)),
                ('shipping_price', models.FloatField(null=True)),
                ('currency', models.CharField(choices=[('CAD', 'Canada Dollars'), ('USD', 'United States Dollars')], max_length=3, null=True)),
            ],
        ),
    ]
